//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace DecisionModelNotation.Shema {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("definitions", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tDefinitions : tNamedElement {
        
        private tImport[] importField;
        
        private tItemDefinition[] itemDefinitionField;
        
        private tDRGElement[] itemsField;
        
        private tArtifact[] items1Field;
        
        private tElementCollection[] elementCollectionField;
        
        private tBusinessContextElement[] items2Field;
        
        private string expressionLanguageField;
        
        private string typeLanguageField;
        
        private string namespaceField;
        
        private string exporterField;
        
        private string exporterVersionField;
        
        public tDefinitions() {
            this.expressionLanguageField = "http://www.omg.org/spec/FEEL/20140401";
            this.typeLanguageField = "http://www.omg.org/spec/FEEL/20140401";
            this.@namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd";
        }
        
        /// <remarks/>
        [XmlElement("import")]
        public tImport[] import {
            get {
                return this.importField;
            }
            set {
                this.importField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("itemDefinition")]
        public tItemDefinition[] itemDefinition {
            get {
                return this.itemDefinitionField;
            }
            set {
                this.itemDefinitionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("businessKnowledgeModel", typeof(tBusinessKnowledgeModel))]
        [XmlElement("decision", typeof(tDecision))]
        [XmlElement("inputData", typeof(tInputData))]
        [XmlElement("knowledgeSource", typeof(tKnowledgeSource))]
        public tDRGElement[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("association", typeof(tAssociation))]
        [XmlElement("textAnnotation", typeof(tTextAnnotation))]
        public tArtifact[] Items1 {
            get {
                return this.items1Field;
            }
            set {
                this.items1Field = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("elementCollection")]
        public tElementCollection[] elementCollection {
            get {
                return this.elementCollectionField;
            }
            set {
                this.elementCollectionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("organizationUnit", typeof(tOrganizationUnit))]
        [XmlElement("performanceIndicator", typeof(tPerformanceIndicator))]
        public tBusinessContextElement[] Items2 {
            get {
                return this.items2Field;
            }
            set {
                this.items2Field = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        [System.ComponentModel.DefaultValueAttribute("http://www.omg.org/spec/FEEL/20140401")]
        public string expressionLanguage {
            get {
                return this.expressionLanguageField;
            }
            set {
                this.expressionLanguageField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        [System.ComponentModel.DefaultValueAttribute("http://www.omg.org/spec/FEEL/20140401")]
        public string typeLanguage {
            get {
                return this.typeLanguageField;
            }
            set {
                this.typeLanguageField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string @namespace {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string exporter {
            get {
                return this.exporterField;
            }
            set {
                this.exporterField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string exporterVersion {
            get {
                return this.exporterVersionField;
            }
            set {
                this.exporterVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [XmlInclude(typeof(tImportedValues))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("import", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tImport {
        
        private string namespaceField;
        
        private string locationURIField;
        
        private string importTypeField;
        
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string @namespace {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string locationURI {
            get {
                return this.locationURIField;
            }
            set {
                this.locationURIField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string importType {
            get {
                return this.importTypeField;
            }
            set {
                this.importTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class tBinding {
        
        private tInformationItem parameterField;
        
        private tExpression itemField;
        
        /// <remarks/>
        public tInformationItem parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("context", typeof(tContext))]
        [XmlElement("decisionTable", typeof(tDecisionTable))]
        [XmlElement("functionDefinition", typeof(tFunctionDefinition))]
        [XmlElement("invocation", typeof(tInvocation))]
        [XmlElement("list", typeof(tList))]
        [XmlElement("literalExpression", typeof(tLiteralExpression))]
        [XmlElement("relation", typeof(tRelation))]
        public tExpression Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("informationItem", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tInformationItem : tNamedElement {
        
        private System.Xml.XmlQualifiedName typeRefField;
        
        /// <remarks/>
        [XmlAttribute()]
        public System.Xml.XmlQualifiedName typeRef {
            get {
                return this.typeRefField;
            }
            set {
                this.typeRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [XmlInclude(typeof(tDecisionService))]
    [XmlInclude(typeof(tBusinessContextElement))]
    [XmlInclude(typeof(tOrganizationUnit))]
    [XmlInclude(typeof(tPerformanceIndicator))]
    [XmlInclude(typeof(tElementCollection))]
    [XmlInclude(typeof(tInformationItem))]
    [XmlInclude(typeof(tDRGElement))]
    [XmlInclude(typeof(tKnowledgeSource))]
    [XmlInclude(typeof(tInputData))]
    [XmlInclude(typeof(tBusinessKnowledgeModel))]
    [XmlInclude(typeof(tDecision))]
    [XmlInclude(typeof(tItemDefinition))]
    [XmlInclude(typeof(tDefinitions))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class tNamedElement : tDMNElement {
        
        private string nameField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [XmlInclude(typeof(tArtifact))]
    [XmlInclude(typeof(tAssociation))]
    [XmlInclude(typeof(tTextAnnotation))]
    [XmlInclude(typeof(tNamedElement))]
    [XmlInclude(typeof(tDecisionService))]
    [XmlInclude(typeof(tBusinessContextElement))]
    [XmlInclude(typeof(tOrganizationUnit))]
    [XmlInclude(typeof(tPerformanceIndicator))]
    [XmlInclude(typeof(tElementCollection))]
    [XmlInclude(typeof(tInformationItem))]
    [XmlInclude(typeof(tDRGElement))]
    [XmlInclude(typeof(tKnowledgeSource))]
    [XmlInclude(typeof(tInputData))]
    [XmlInclude(typeof(tBusinessKnowledgeModel))]
    [XmlInclude(typeof(tDecision))]
    [XmlInclude(typeof(tItemDefinition))]
    [XmlInclude(typeof(tDefinitions))]
    [XmlInclude(typeof(tDecisionRule))]
    [XmlInclude(typeof(tOutputClause))]
    [XmlInclude(typeof(tUnaryTests))]
    [XmlInclude(typeof(tInputClause))]
    [XmlInclude(typeof(tExpression))]
    [XmlInclude(typeof(tList))]
    [XmlInclude(typeof(tRelation))]
    [XmlInclude(typeof(tFunctionDefinition))]
    [XmlInclude(typeof(tContext))]
    [XmlInclude(typeof(tDecisionTable))]
    [XmlInclude(typeof(tInvocation))]
    [XmlInclude(typeof(tLiteralExpression))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class tDMNElement {
        
        private string descriptionField;
        
        private tDMNElementExtensionElements extensionElementsField;
        
        private string idField;
        
        private string labelField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public tDMNElementExtensionElements extensionElements {
            get {
                return this.extensionElementsField;
            }
            set {
                this.extensionElementsField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class tDMNElementExtensionElements {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [XmlInclude(typeof(tAssociation))]
    [XmlInclude(typeof(tTextAnnotation))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class tArtifact : tDMNElement {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class tDecisionRule : tDMNElement {
        
        private tUnaryTests[] inputEntryField;
        
        private tLiteralExpression[] outputEntryField;
        
        /// <remarks/>
        [XmlElement("inputEntry")]
        public tUnaryTests[] inputEntry {
            get {
                return this.inputEntryField;
            }
            set {
                this.inputEntryField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("outputEntry")]
        public tLiteralExpression[] outputEntry {
            get {
                return this.outputEntryField;
            }
            set {
                this.outputEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class tUnaryTests : tDMNElement {
        
        private string textField;
        
        private string expressionLanguageField;
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string expressionLanguage {
            get {
                return this.expressionLanguageField;
            }
            set {
                this.expressionLanguageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("literalExpression", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tLiteralExpression : tExpression {
        
        private object itemField;
        
        private string expressionLanguageField;
        
        /// <remarks/>
        [XmlElement("importedValues", typeof(tImportedValues))]
        [XmlElement("text", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string expressionLanguage {
            get {
                return this.expressionLanguageField;
            }
            set {
                this.expressionLanguageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class tImportedValues : tImport {
        
        private string importedElementField;
        
        private string expressionLanguageField;
        
        /// <remarks/>
        public string importedElement {
            get {
                return this.importedElementField;
            }
            set {
                this.importedElementField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string expressionLanguage {
            get {
                return this.expressionLanguageField;
            }
            set {
                this.expressionLanguageField = value;
            }
        }
    }
    
    /// <remarks/>
    [XmlInclude(typeof(tList))]
    [XmlInclude(typeof(tRelation))]
    [XmlInclude(typeof(tFunctionDefinition))]
    [XmlInclude(typeof(tContext))]
    [XmlInclude(typeof(tDecisionTable))]
    [XmlInclude(typeof(tInvocation))]
    [XmlInclude(typeof(tLiteralExpression))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class tExpression : tDMNElement {
        
        private System.Xml.XmlQualifiedName typeRefField;
        
        /// <remarks/>
        [XmlAttribute()]
        public System.Xml.XmlQualifiedName typeRef {
            get {
                return this.typeRefField;
            }
            set {
                this.typeRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class tOutputClause : tDMNElement {
        
        private tUnaryTests outputValuesField;
        
        private tLiteralExpression defaultOutputEntryField;
        
        private string nameField;
        
        private System.Xml.XmlQualifiedName typeRefField;
        
        /// <remarks/>
        public tUnaryTests outputValues {
            get {
                return this.outputValuesField;
            }
            set {
                this.outputValuesField = value;
            }
        }
        
        /// <remarks/>
        public tLiteralExpression defaultOutputEntry {
            get {
                return this.defaultOutputEntryField;
            }
            set {
                this.defaultOutputEntryField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public System.Xml.XmlQualifiedName typeRef {
            get {
                return this.typeRefField;
            }
            set {
                this.typeRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class tInputClause : tDMNElement {
        
        private tLiteralExpression inputExpressionField;
        
        private tUnaryTests inputValuesField;
        
        /// <remarks/>
        public tLiteralExpression inputExpression {
            get {
                return this.inputExpressionField;
            }
            set {
                this.inputExpressionField = value;
            }
        }
        
        /// <remarks/>
        public tUnaryTests inputValues {
            get {
                return this.inputValuesField;
            }
            set {
                this.inputValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [XmlInclude(typeof(tOrganizationUnit))]
    [XmlInclude(typeof(tPerformanceIndicator))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class tBusinessContextElement : tNamedElement {
        
        private string uRIField;
        
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
    }
    
    /// <remarks/>
    [XmlInclude(typeof(tKnowledgeSource))]
    [XmlInclude(typeof(tInputData))]
    [XmlInclude(typeof(tBusinessKnowledgeModel))]
    [XmlInclude(typeof(tDecision))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class tDRGElement : tNamedElement {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("context", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tContext : tExpression {
        
        private tContextEntry[] contextEntryField;
        
        /// <remarks/>
        [XmlElement("contextEntry")]
        public tContextEntry[] contextEntry {
            get {
                return this.contextEntryField;
            }
            set {
                this.contextEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class tContextEntry {
        
        private tInformationItem variableField;
        
        private tExpression itemField;
        
        /// <remarks/>
        public tInformationItem variable {
            get {
                return this.variableField;
            }
            set {
                this.variableField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("context", typeof(tContext))]
        [XmlElement("decisionTable", typeof(tDecisionTable))]
        [XmlElement("functionDefinition", typeof(tFunctionDefinition))]
        [XmlElement("invocation", typeof(tInvocation))]
        [XmlElement("list", typeof(tList))]
        [XmlElement("literalExpression", typeof(tLiteralExpression))]
        [XmlElement("relation", typeof(tRelation))]
        public tExpression Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("decisionTable", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tDecisionTable : tExpression {
        
        private tInputClause[] inputField;
        
        private tOutputClause[] outputField;
        
        private tDecisionRule[] ruleField;
        
        private tHitPolicy hitPolicyField;
        
        private tBuiltinAggregator aggregationField;
        
        private bool aggregationFieldSpecified;
        
        private tDecisionTableOrientation preferredOrientationField;
        
        private string outputLabelField;
        
        public tDecisionTable() {
            this.hitPolicyField = tHitPolicy.UNIQUE;
            this.preferredOrientationField = tDecisionTableOrientation.RuleasRow;
        }
        
        /// <remarks/>
        [XmlElement("input")]
        public tInputClause[] input {
            get {
                return this.inputField;
            }
            set {
                this.inputField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("output")]
        public tOutputClause[] output {
            get {
                return this.outputField;
            }
            set {
                this.outputField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("rule")]
        public tDecisionRule[] rule {
            get {
                return this.ruleField;
            }
            set {
                this.ruleField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(tHitPolicy.UNIQUE)]
        public tHitPolicy hitPolicy {
            get {
                return this.hitPolicyField;
            }
            set {
                this.hitPolicyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public tBuiltinAggregator aggregation {
            get {
                return this.aggregationField;
            }
            set {
                this.aggregationField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool aggregationSpecified {
            get {
                return this.aggregationFieldSpecified;
            }
            set {
                this.aggregationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(tDecisionTableOrientation.RuleasRow)]
        public tDecisionTableOrientation preferredOrientation {
            get {
                return this.preferredOrientationField;
            }
            set {
                this.preferredOrientationField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string outputLabel {
            get {
                return this.outputLabelField;
            }
            set {
                this.outputLabelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public enum tHitPolicy {
        
        /// <remarks/>
        UNIQUE,
        
        /// <remarks/>
        FIRST,
        
        /// <remarks/>
        PRIORITY,
        
        /// <remarks/>
        ANY,
        
        /// <remarks/>
        COLLECT,
        
        /// <remarks/>
        [XmlEnum("RULE ORDER")]
        RULEORDER,
        
        /// <remarks/>
        [XmlEnum("OUTPUT ORDER")]
        OUTPUTORDER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public enum tBuiltinAggregator {
        
        /// <remarks/>
        SUM,
        
        /// <remarks/>
        COUNT,
        
        /// <remarks/>
        MIN,
        
        /// <remarks/>
        MAX,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public enum tDecisionTableOrientation {
        
        /// <remarks/>
        [XmlEnum("Rule-as-Row")]
        RuleasRow,
        
        /// <remarks/>
        [XmlEnum("Rule-as-Column")]
        RuleasColumn,
        
        /// <remarks/>
        CrossTable,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("functionDefinition", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tFunctionDefinition : tExpression {
        
        private tInformationItem[] formalParameterField;
        
        private tExpression itemField;
        
        /// <remarks/>
        [XmlElement("formalParameter")]
        public tInformationItem[] formalParameter {
            get {
                return this.formalParameterField;
            }
            set {
                this.formalParameterField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("context", typeof(tContext))]
        [XmlElement("decisionTable", typeof(tDecisionTable))]
        [XmlElement("functionDefinition", typeof(tFunctionDefinition))]
        [XmlElement("invocation", typeof(tInvocation))]
        [XmlElement("list", typeof(tList))]
        [XmlElement("literalExpression", typeof(tLiteralExpression))]
        [XmlElement("relation", typeof(tRelation))]
        public tExpression Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("invocation", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tInvocation : tExpression {
        
        private tExpression itemField;
        
        private tBinding[] bindingField;
        
        /// <remarks/>
        [XmlElement("context", typeof(tContext))]
        [XmlElement("decisionTable", typeof(tDecisionTable))]
        [XmlElement("functionDefinition", typeof(tFunctionDefinition))]
        [XmlElement("invocation", typeof(tInvocation))]
        [XmlElement("list", typeof(tList))]
        [XmlElement("literalExpression", typeof(tLiteralExpression))]
        [XmlElement("relation", typeof(tRelation))]
        public tExpression Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("binding")]
        public tBinding[] binding {
            get {
                return this.bindingField;
            }
            set {
                this.bindingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("list", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tList : tExpression {
        
        private tExpression[] itemsField;
        
        /// <remarks/>
        [XmlElement("context", typeof(tContext))]
        [XmlElement("decisionTable", typeof(tDecisionTable))]
        [XmlElement("functionDefinition", typeof(tFunctionDefinition))]
        [XmlElement("invocation", typeof(tInvocation))]
        [XmlElement("list", typeof(tList))]
        [XmlElement("literalExpression", typeof(tLiteralExpression))]
        [XmlElement("relation", typeof(tRelation))]
        public tExpression[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("relation", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tRelation : tExpression {
        
        private tInformationItem[] columnField;
        
        private tList[] rowField;
        
        /// <remarks/>
        [XmlElement("column")]
        public tInformationItem[] column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("row")]
        public tList[] row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class tAuthorityRequirement {
        
        private tDMNElementReference itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        /// <remarks/>
        [XmlElement("requiredAuthority", typeof(tDMNElementReference))]
        [XmlElement("requiredDecision", typeof(tDMNElementReference))]
        [XmlElement("requiredInput", typeof(tDMNElementReference))]
        [XmlChoiceIdentifier("ItemElementName")]
        public tDMNElementReference Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class tDMNElementReference {
        
        private string hrefField;
        
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        requiredAuthority,
        
        /// <remarks/>
        requiredDecision,
        
        /// <remarks/>
        requiredInput,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class tKnowledgeRequirement {
        
        private tDMNElementReference requiredKnowledgeField;
        
        /// <remarks/>
        public tDMNElementReference requiredKnowledge {
            get {
                return this.requiredKnowledgeField;
            }
            set {
                this.requiredKnowledgeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class tInformationRequirement {
        
        private tDMNElementReference itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [XmlElement("requiredDecision", typeof(tDMNElementReference))]
        [XmlElement("requiredInput", typeof(tDMNElementReference))]
        [XmlChoiceIdentifier("ItemElementName")]
        public tDMNElementReference Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        requiredDecision,
        
        /// <remarks/>
        requiredInput,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("itemDefinition", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tItemDefinition : tNamedElement {
        
        private object[] itemsField;
        
        private string typeLanguageField;
        
        private bool isCollectionField;
        
        public tItemDefinition() {
            this.isCollectionField = false;
        }
        
        /// <remarks/>
        [XmlElement("allowedValues", typeof(tUnaryTests))]
        [XmlElement("itemComponent", typeof(tItemDefinition))]
        [XmlElement("typeRef", typeof(System.Xml.XmlQualifiedName))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string typeLanguage {
            get {
                return this.typeLanguageField;
            }
            set {
                this.typeLanguageField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool isCollection {
            get {
                return this.isCollectionField;
            }
            set {
                this.isCollectionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("businessKnowledgeModel", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tBusinessKnowledgeModel : tDRGElement {
        
        private tFunctionDefinition encapsulatedLogicField;
        
        private tInformationItem variableField;
        
        private tKnowledgeRequirement[] knowledgeRequirementField;
        
        private tAuthorityRequirement[] authorityRequirementField;
        
        /// <remarks/>
        public tFunctionDefinition encapsulatedLogic {
            get {
                return this.encapsulatedLogicField;
            }
            set {
                this.encapsulatedLogicField = value;
            }
        }
        
        /// <remarks/>
        public tInformationItem variable {
            get {
                return this.variableField;
            }
            set {
                this.variableField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("knowledgeRequirement")]
        public tKnowledgeRequirement[] knowledgeRequirement {
            get {
                return this.knowledgeRequirementField;
            }
            set {
                this.knowledgeRequirementField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("authorityRequirement")]
        public tAuthorityRequirement[] authorityRequirement {
            get {
                return this.authorityRequirementField;
            }
            set {
                this.authorityRequirementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("decision", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tDecision : tDRGElement {
        
        private string questionField;
        
        private string allowedAnswersField;
        
        private tInformationItem variableField;
        
        private tInformationRequirement[] informationRequirementField;
        
        private tKnowledgeRequirement[] knowledgeRequirementField;
        
        private tAuthorityRequirement[] authorityRequirementField;
        
        private tDMNElementReference[] supportedObjectiveField;
        
        private tDMNElementReference[] impactedPerformanceIndicatorField;
        
        private tDMNElementReference[] decisionMakerField;
        
        private tDMNElementReference[] decisionOwnerField;
        
        private tDMNElementReference[] usingProcessField;
        
        private tDMNElementReference[] usingTaskField;
        
        private tExpression itemField;
        
        /// <remarks/>
        public string question {
            get {
                return this.questionField;
            }
            set {
                this.questionField = value;
            }
        }
        
        /// <remarks/>
        public string allowedAnswers {
            get {
                return this.allowedAnswersField;
            }
            set {
                this.allowedAnswersField = value;
            }
        }
        
        /// <remarks/>
        public tInformationItem variable {
            get {
                return this.variableField;
            }
            set {
                this.variableField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("informationRequirement")]
        public tInformationRequirement[] informationRequirement {
            get {
                return this.informationRequirementField;
            }
            set {
                this.informationRequirementField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("knowledgeRequirement")]
        public tKnowledgeRequirement[] knowledgeRequirement {
            get {
                return this.knowledgeRequirementField;
            }
            set {
                this.knowledgeRequirementField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("authorityRequirement")]
        public tAuthorityRequirement[] authorityRequirement {
            get {
                return this.authorityRequirementField;
            }
            set {
                this.authorityRequirementField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("supportedObjective")]
        public tDMNElementReference[] supportedObjective {
            get {
                return this.supportedObjectiveField;
            }
            set {
                this.supportedObjectiveField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("impactedPerformanceIndicator")]
        public tDMNElementReference[] impactedPerformanceIndicator {
            get {
                return this.impactedPerformanceIndicatorField;
            }
            set {
                this.impactedPerformanceIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("decisionMaker")]
        public tDMNElementReference[] decisionMaker {
            get {
                return this.decisionMakerField;
            }
            set {
                this.decisionMakerField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("decisionOwner")]
        public tDMNElementReference[] decisionOwner {
            get {
                return this.decisionOwnerField;
            }
            set {
                this.decisionOwnerField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("usingProcess")]
        public tDMNElementReference[] usingProcess {
            get {
                return this.usingProcessField;
            }
            set {
                this.usingProcessField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("usingTask")]
        public tDMNElementReference[] usingTask {
            get {
                return this.usingTaskField;
            }
            set {
                this.usingTaskField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("context", typeof(tContext))]
        [XmlElement("decisionTable", typeof(tDecisionTable))]
        [XmlElement("functionDefinition", typeof(tFunctionDefinition))]
        [XmlElement("invocation", typeof(tInvocation))]
        [XmlElement("list", typeof(tList))]
        [XmlElement("literalExpression", typeof(tLiteralExpression))]
        [XmlElement("relation", typeof(tRelation))]
        public tExpression Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("inputData", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tInputData : tDRGElement {
        
        private tInformationItem variableField;
        
        /// <remarks/>
        public tInformationItem variable {
            get {
                return this.variableField;
            }
            set {
                this.variableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("knowledgeSource", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tKnowledgeSource : tDRGElement {
        
        private tAuthorityRequirement[] authorityRequirementField;
        
        private string typeField;
        
        private tDMNElementReference ownerField;
        
        private string locationURIField;
        
        /// <remarks/>
        [XmlElement("authorityRequirement")]
        public tAuthorityRequirement[] authorityRequirement {
            get {
                return this.authorityRequirementField;
            }
            set {
                this.authorityRequirementField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public tDMNElementReference owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string locationURI {
            get {
                return this.locationURIField;
            }
            set {
                this.locationURIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("association", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tAssociation : tArtifact {
        
        private tDMNElementReference sourceRefField;
        
        private tDMNElementReference targetRefField;
        
        private tAssociationDirection associationDirectionField;
        
        public tAssociation() {
            this.associationDirectionField = tAssociationDirection.None;
        }
        
        /// <remarks/>
        public tDMNElementReference sourceRef {
            get {
                return this.sourceRefField;
            }
            set {
                this.sourceRefField = value;
            }
        }
        
        /// <remarks/>
        public tDMNElementReference targetRef {
            get {
                return this.targetRefField;
            }
            set {
                this.targetRefField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(tAssociationDirection.None)]
        public tAssociationDirection associationDirection {
            get {
                return this.associationDirectionField;
            }
            set {
                this.associationDirectionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public enum tAssociationDirection {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        One,
        
        /// <remarks/>
        Both,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("textAnnotation", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tTextAnnotation : tArtifact {
        
        private string textField;
        
        private string textFormatField;
        
        public tTextAnnotation() {
            this.textFormatField = "text/plain";
        }
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute("text/plain")]
        public string textFormat {
            get {
                return this.textFormatField;
            }
            set {
                this.textFormatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("elementCollection", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tElementCollection : tNamedElement {
        
        private tDMNElementReference[] drgElementField;
        
        /// <remarks/>
        [XmlElement("drgElement")]
        public tDMNElementReference[] drgElement {
            get {
                return this.drgElementField;
            }
            set {
                this.drgElementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("organizationUnit", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tOrganizationUnit : tBusinessContextElement {
        
        private tDMNElementReference[] decisionMadeField;
        
        private tDMNElementReference[] decisionOwnedField;
        
        /// <remarks/>
        [XmlElement("decisionMade")]
        public tDMNElementReference[] decisionMade {
            get {
                return this.decisionMadeField;
            }
            set {
                this.decisionMadeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("decisionOwned")]
        public tDMNElementReference[] decisionOwned {
            get {
                return this.decisionOwnedField;
            }
            set {
                this.decisionOwnedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("performanceIndicator", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tPerformanceIndicator : tBusinessContextElement {
        
        private tDMNElementReference[] impactingDecisionField;
        
        /// <remarks/>
        [XmlElement("impactingDecision")]
        public tDMNElementReference[] impactingDecision {
            get {
                return this.impactingDecisionField;
            }
            set {
                this.impactingDecisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [XmlRoot("decisionService", Namespace="http://www.omg.org/spec/DMN/20151101/dmn.xsd", IsNullable=false)]
    public partial class tDecisionService : tNamedElement {
        
        private tDMNElementReference[] outputDecisionField;
        
        private tDMNElementReference[] encapsulatedDecisionField;
        
        private tDMNElementReference[] inputDecisionField;
        
        private tDMNElementReference[] inputDataField;
        
        /// <remarks/>
        [XmlElement("outputDecision")]
        public tDMNElementReference[] outputDecision {
            get {
                return this.outputDecisionField;
            }
            set {
                this.outputDecisionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("encapsulatedDecision")]
        public tDMNElementReference[] encapsulatedDecision {
            get {
                return this.encapsulatedDecisionField;
            }
            set {
                this.encapsulatedDecisionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("inputDecision")]
        public tDMNElementReference[] inputDecision {
            get {
                return this.inputDecisionField;
            }
            set {
                this.inputDecisionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("inputData")]
        public tDMNElementReference[] inputData {
            get {
                return this.inputDataField;
            }
            set {
                this.inputDataField = value;
            }
        }
    }
}
